host = "0.0.0.0"
port = 8000

#chat_configs = []
[[chat_configs]]
model_id = "/Users/hubertshelley/Documents/machine_learn/yi-chat-6B-GGUF/yi-chat-6b.Q5_K_M.gguf"
alias = "yi-chat-6b.Q5_K_M.gguf"
# 目前candle尚不支持gpu
cpu = false
gqa = 1
tokenizer = "/Users/hubertshelley/Documents/machine_learn/Yi-6B-Chat/tokenizer.json"
# 聊天模型配置列表

# 语音转文字模型配置列表
whisper_configs = []
#[[whisper_configs]]
#model_id = "/Users/hubertshelley/Documents/machine_learn/whisper-large-v3"
#alias = "large-v3"
#cpu = false

