host = "127.0.0.1"
port = 8000

chat_configs = []
# 聊天模型配置列表

# 语音转文字模型配置列表
[[whisper_configs]]
model_id = "/Users/hubertshelley/Documents/machine_learn/whisper-large-v3"
alias = "large-v3"
cpu = false

