[tool.poetry]
name = "llm-server-test"
version = "0.1.0"
description = ""
authors = ["hubertshelley <hubertshelley@163.com>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
