host = "0.0.0.0"
port = 8080

chat_configs = []
# 聊天模型配置列表

# 语音转文字模型配置列表
# #[derive(Clone, Debug, Deserialize)]
#pub(crate) struct WhisperModelConfig {
#    pub(crate) model_id: String,
#    pub(crate) alias: String,
#    #[serde(default = "default_cpu")]
#    pub(crate) cpu: bool,
#    #[serde(default = "default_seed")]
#    pub(crate) seed: u64,
#    #[serde(default = "default_quantized")]
#    pub(crate) quantized: bool,
#}
[[whisper_configs]]
model_id = "whisper"
alias = "whisper"

